title:
    prefix : /
    type : annotation
    resource : "@KingdomFrontBundle/Controller/TitleController.php"
  
login:
    prefix : /login/
    type : annotation
    resource : "@KingdomFrontBundle/Controller/LoginController.php"

    
login_check:
    pattern : /login_check
    
logout :
    pattern : /logout
    
mypage:
    prefix : /mypage/
    type : annotation
    resource : "@KingdomFrontBundle/Controller/MypageController.php"

product:
    prefix : /product/
    type : annotation
    resource : "@KingdomFrontBundle/Controller/ProductController.php"
